[package]
name = "ua4f"
authors = ["James Clef"]
license = "AGPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
log = "0.4.22"
log4rs = "1.3.0"
socks5-server = "0.10.1"
tokio = { version = "1.40.0", features = ["full"] }
